### ISSUE TITLE
Incompatible with latest Ionic2 app scripts/webpack

### ISSUE THREAD

**Issue by digitaltopo** [backand/angular2bknd-sdk#1]
On a fresh ionic2 project, we get the following error:

`index.ts:1 Uncaught Error: Module build failed: TypeError: Cannot read property 'content' of undefined`
at
`Object.typescriptSourcemapLoaderMemory (/path/to/project/node_modules/@ionic/app-scripts/dist/webpack/typescript-sourcemap-loader-memory.js:21:34)`

```
  "dependencies": {
    "@angular/common": "2.1.1",
    "@angular/compiler": "2.1.1",
    "@angular/compiler-cli": "2.1.1",
    "@angular/core": "2.1.1",
    "@angular/forms": "2.1.1",
    "@angular/http": "2.1.1",
    "@angular/platform-browser": "2.1.1",
    "@angular/platform-browser-dynamic": "2.1.1",
    "@angular/platform-server": "2.1.1",
    "@ionic/storage": "1.1.6",
    "angular2bknd-sdk": "^3.1.1",
    "ionic-angular": "2.0.0-rc.3",
    "ionic-native": "2.2.3",
    "ionicons": "3.0.0",
    "rxjs": "5.0.0-beta.12",
    "zone.js": "0.6.26"
  },
  "devDependencies": {
    "@ionic/app-scripts": "0.0.45",
    "@types/node": "^6.0.51",
    "@types/socket.io-client": "^1.4.29",
    "typescript": "2.0.6"
  },
```

**Comment by henriquezago** [comment]
I'm also having this problem.

**Comment by digitaltopo** [comment]
Since this SDK module is essentially just a single Angular2 provider component right now, you can just add `backandService.ts` into your project manually and it should work fine. There must be something up with the packaging... 

This a great start though!!

**Comment by kornatzky** [comment]
We were not able to reproduce the issue. Using Ionic version 2.1.12
And following the installations instructions. 

```
npm install angular2bknd-sdk --save
npm install @types/node --save-dev
npm install @types/socket.io-client --save-dev 
```
