### ISSUE TITLE
 No provider for Http!

### ISSUE THREAD

**Issue by ricricucit** [backand/angular2bknd-sdk#5]
I followed all your instructions and ended up with a `No provider for Http!`.

Since I'm using [this](https://github.com/qdouble/angular-webpack2-starter/tree/no-universal-support) as starter, my **app.module.ts** has `import { HttpModule } from '@angular/http';` ...so ATM I'm really sure what's causing the problem...any idea?

**Comment by ricricucit** [comment]
seems to be an angular version problem....

**Comment by kornatzky** [comment]
We have built an example using Angular CLI.
https://github.com/kornatzky/backand-angularjs2
Can you use Angular CLI?
We will check your case later.

**Comment by ricricucit** [comment]
I'd prefer to use this SDK since it's much simpler (and since angular CLI is still in beta...)
If you can just point out what could be the main problem I could take a look at it myself.

**Comment by ricricucit** [comment]
just trying to keep this issue alive. @kornatzky did you have time to check?

**Comment by kornatzky** [comment]
We have been able to reproduce the issue. But we do not have a solution yet.

**Comment by kornatzky** [comment]
We have  successfully integrated the starter with a new SDK. Please use the repo:
[Angular Webpack 2 Starter with Backand](https://github.com/kornatzky/angular-webpack2-starter-backand) that works

**Comment by ricricucit** [comment]
This is not what I'm looking for.  Why would I use a complete new starter? I already have my own.

Do you have anything more similar to _angular2bknd-sdk_ ...or can you give me instructions on what should I look for inside your Starter? Thank you.
