### ISSUE TITLE
Token expiration question

### ISSUE THREAD

**Issue by mdocter** [backand/angular2bknd-sdk#6]
Hi guys,

I'm using a modified version of the 'angular2bknd-sdk/backandService.ts' in a Vue 2 project.
Can you tell me how token expiration is handled in this service? Does it get a new token as soon as the expiration time is reached? Or do I have to do something myself? 
Any help is appreciated.

Kind regards,

Maarten

**Comment by kornatzky** [comment]
This SDK has no token expiration support. Please switch to our new SDK:
https://github.com/backand/angular2-sdk

**Comment by itayher** [comment]
We about to release much more comprehensive SDK, it it is in closed beta and I will appreciate your feedback. for the Vue project, I suggest you use vanilla SDK (the new Angular 2 is based on Vanilla), located here: https://github.com/backand/vanilla-sdk

Sorry for the confusion, but we are in a transition period to the new SDK.

**Comment by mdocter** [comment]
Thanks for the quick reply. I will try the vanilla sdk. Any ETA for the new sdk? Or can I join the closed beta?

**Comment by evilstickthem** [comment]
Hi @mdocter, we actually have the SDK in beta test now. You can find the SDK at https://github.com/backand/vanilla-sdk - the README should contain all the information you need to get started. If there's anything there that doesn't make sense, or anything you'd like to see more information on once you've worked with the SDK, let us know! There's also an angular 2 SDK as mentioned above, that wraps the vanilla SDK and allows it to be easily integrated with Angular 2 apps

**Comment by mdocter** [comment]
@evilstickman Hi Matt, I'm confused now. So the closed Beta mentioned by @itayher is already in the open? In that case @itayher would have known that? Or not?
